<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class commonData extends Model
{
    //Const Activities
    const ACT_CULTO_MARTES = 1000;
    const ACT_AYUNO_MIERCOLES = 1001;
    const ACT_CULTO_JUEVES = 1002;
    const ACT_REFUGIO_JOVENES = 1003;

    //Const code Gedeón
    const GEDEON_SANDIEGO_1 = 2001;
    const GEDEON_SANDIEGO_2 = 2002;
    const GEDEON_SANDIEGO_3 = 2003;
    const GEDEON_SANRAFAEL_1 = 2004;
    const GEDEON_SANRAFAEL_2 = 2005;
    const GEDEON_TRESRIOS_1 = 2006;
    const GEDEON_TRESRIOS_2 = 2007;
    const GEDEON_TRESRIOS_3 = 2008;
    const GEDEON_TRESRIOS_4 = 2009;
    const GEDEON_TRESRIOS_5 = 2010;
    const GEDEON_CONCEPCION_1 = 2011;
    const GEDEON_CONCEPCION_2 = 2012;
    const GEDEON_CONCEPCION_3 = 2013;
    const GEDEON_DULCENOMBRE_1 = 2014;
    const GEDEON_SANJUAN_1 = 2015;
    const GEDEON_CARTAGO_1 = 2016;

    //const roomNames
    const ROOM_CULTO_MARTES = 'CMP_CULTO_MARTES';
    const ROOM_AYUNO_MIERCOLES = 'CMP_AYUNO_MIERCOLES';
    const ROOM_CULTO_JUEVES = 'CMP_CULTO_JUVES';
    const ROOM_REFUGIO_JOVENES = 'CMP_REFUGIO_JOVENES';
    const ROOM_GED_SANDIEGO_1 = 'CMP_GEDEON_SAN_DIEGO_1';
    const ROOM_GED_SANDIEGO_2 = 'CMP_GEDEON_SAN_DIEGO_2';
    const ROOM_GED_SANDIEGO_3 = 'CMP_GEDEON_SAN_DIEGO_3';
    const ROOM_GED_SANRAFAEL_1 = 'CMP_GEDEON_SAN_SAN_RAFAEL_1';
    const ROOM_GED_SANRAFAEL_2 = 'CMP_GEDEON_SAN_SAN_RAFAEL_2';
    const ROOM_GED_TRESRIOS_1 = 'CMP_GEDEON_TRES_RIOS_1';
    const ROOM_GED_TRESRIOS_2 = 'CMP_GEDEON_TRES_RIOS_2';
    const ROOM_GED_MVD = 'CMP_GEDEON_MVD';
    const ROOM_GED_TRESRIOS_4 = 'CMP_GEDEON_TRES_RIOS_4';
    const ROOM_GED_TRESRIOS_5 = 'CMP_GEDEON_TRES_RIOS_5';
    const ROOM_GED_CONCEPCION_1 = 'CMP_GEDEON_CONCEPCION_1';
    const ROOM_GED_CONCEPCION_2 = 'CMP_GEDEON_CONCEPCION_2';
    const ROOM_GED_CONCEPCION_3 = 'CMP_GEDEON_CONCEPCION_3';
    const ROOM_GED_DULCENOMBRE_1 = 'CMP_GEDEON_DULCE_NOMBRE_1';
    const ROOM_GED_SANJUAN_1 = 'CMP_GEDEON_SAN_JUAN_1';
    const ROOM_GED_CARTAGO_1 = 'CMP_GEDEON_CARTAGO_1';
}
